# Generated by Django 4.2.2 on 2023-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_student_email_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('checked_out', 'Checked Out'), ('Available', 'Available'), ('reserved', 'Reserved')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='example@kyu.com', max_length=30),
        ),
    ]
